name: flutter_tests
description: A new Flutter module project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-149.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.3.8
  mockito: ^5.4.0
  path: ^1.8.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/icons/
    - assets/database.db

  module:
    androidX: true
    androidPackage: com.example.flutter_tests
    iosBundleIdentifier: com.example.flutterTests
