name: flutter_tests
description: A new Flutter module project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-149.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  provider: ^6.0.5


flutter:
  uses-material-design: true

  assets:
    - res/icons/
    - assets/database.db

  module:
    androidX: true
    androidPackage: com.example.flutter_tests
    iosBundleIdentifier: com.example.flutterTests
