// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_tests/test/calculator/calculator_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_tests/calculator/domain/model/operation.dart' as _i4;
import 'package:flutter_tests/calculator/infrastructure/calculator_repository_sqlite.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CalculatorRepositorySqlite].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculatorRepositorySqlite extends _i1.Mock
    implements _i2.CalculatorRepositorySqlite {
  MockCalculatorRepositorySqlite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Operation>> getOperations() => (super.noSuchMethod(
        Invocation.method(
          #getOperations,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Operation>>.value(<_i4.Operation>[]),
      ) as _i3.Future<List<_i4.Operation>>);
  @override
  _i3.Future<bool> saveOperation(_i4.Operation? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOperation,
          [operation],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [Operation].
///
/// See the documentation for Mockito's code generation for more information.
class MockOperation extends _i1.Mock implements _i4.Operation {
  MockOperation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get operation => (super.noSuchMethod(
        Invocation.getter(#operation),
        returnValue: 0,
      ) as int);
  @override
  String get result => (super.noSuchMethod(
        Invocation.getter(#result),
        returnValue: '',
      ) as String);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
